#! /usr/bin/python3
from os.path import join, realpath, dirname
import sys

if __name__ == '__main__':
    sys.path.insert(0, join(dirname(realpath(__file__)), 'src'))
    from pyhint import PyHint
    sys.exit(PyHint().main())
